name: build

# see https://repo1.maven.org/maven2/org/openjfx/javafx-base/17.0.7/ for classifiers to use for JavaFX libs

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Gradle
    uses: ./.github/workflows/gradle.yml

