name: Gradle build

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20.0.1'
    - name: Execute Gradle build
      run: ./gradlew assemble --no-daemon
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-binaries
        path: |
          # tar, zip
          build/distributions/**/*
          # main jar
          build/libs/**/*
          build/reports/**/*
