name: release

# see https://repo1.maven.org/maven2/org/openjfx/javafx-base/17.0.7/ for classifiers to use for JavaFX libs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
        