name: release

# see https://repo1.maven.org/maven2/org/openjfx/javafx-base/17.0.7/ for classifiers to use for JavaFX libs

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        required: true
        default: true
      versionNumber:
        type: string
        description: version number; must be in form 'x.y.z' with x >= 1, y >= 0 and z >= 0
        required: true
      versionNotes:
        type: string
        description: Github release notes
        required: true

permissions:
  contents: write

env:
  RELEASE_TAG: ${{ github.event.inputs.production && 'pre' || '' }}release/v${{ github.event.inputs.versionNumber }}${{ github.event.inputs.prerelease && '-PRERELEASE' || '' }}
  RELEASE_TITLE: v${{ github.event.inputs.versionNumber }}${{ github.event.inputs.prerelease && ' pre-release' || '' }}
      
jobs:
  build:
    name: Gradle
    uses: ./.github/workflows/gradle.yml
    with:
      versionNumber: ${{ github.event.inputs.versionNumber }}
  release:
    needs: build
    name: create release
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: create release
        run: gh release create $RELEASE_TAG --title "$RELEASE_TITLE" --notes "${{github.event.inputs.versionNotes}}" ${{ github.event.inputs.production && '--prerelease' || '' }}
        #run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} --generate-notes --prerelease
      - run: ls -la
      - run: ls -la artifacts
      - run: ls -la artifacts/build
      - name: upload jar artifacts to release
        run: gh release upload $RELEASE_TAG artifacts/build/libs/*
        #run: gh release upload ${GITHUB_REF#refs/*/} 12_ft_chrome.zip 12_ft_firefox.zip
      #- name: upload jpackage artifacts to release
      #  run: gh release upload $RELEASE_TAG artifacts/build/jpackage/*
        